name: Sync Anime Profiles and Regex

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 02:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yq
        run: sudo snap install yq

      - name: Create directories
        run: |
          mkdir -p custom_formats
          mkdir -p regex_patterns
          mkdir -p profiles

      # --- Sync Anime 1080p.yml ---
      - name: Mirror Anime 1080p.yml
        run: |
          echo "Downloading Anime 1080p.yml"
          curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/profiles/Anime%201080p.yml" -o "profiles/Anime 1080p.yml"

      # --- Sync custom formats referenced in Anime 1080p.yml ---
      - name: Download custom formats
        run: |
          mapfile -t CUSTOM_FORMATS < <(yq e '.custom_formats[].name' profiles/Anime\ 1080p.yml)
          for FORMAT in "${CUSTOM_FORMATS[@]}"; do
            SAFE_FORMAT=$(echo "$FORMAT" | sed 's/ /%20/g')
            echo "Downloading custom format $FORMAT"
            curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/custom_formats/$SAFE_FORMAT.yml" -o "custom_formats/$FORMAT.yml" || echo "Warning: $FORMAT.yml not found"
          done

      # --- Sync regex patterns referenced in Anime 1080p.yml ---
      - name: Download regex patterns
        run: |
          mkdir -p regex_patterns
          mapfile -t REGEX_PATTERNS < <(yq e '.regex[].name' profiles/Anime\ 1080p.yml)
          for PATTERN in "${REGEX_PATTERNS[@]}"; do
            SAFE_PATTERN=$(echo "$PATTERN" | sed 's/ /%20/g')
            echo "Downloading regex pattern $PATTERN"
            curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/regex_patterns/$SAFE_PATTERN.yml" -o "regex_patterns/$PATTERN.yml" || echo "Warning: $PATTERN.yml not found"
          done
