name: Sync Anime 1080p Custom Formats

on:
  schedule:
    # Runs every day at 3am UTC
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  sync_custom_formats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies and yq
        run: |
          sudo apt-get update && sudo apt-get install -y curl git wget
          # Install Mike Farah yq (Go version) to $HOME/bin
          mkdir -p $HOME/bin
          YQ_VERSION=v4.45.1
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O $HOME/bin/yq
          chmod +x $HOME/bin/yq
          export PATH=$HOME/bin:$PATH
          yq --version

      - name: Download latest anime 1080p.yml from upstream
        run: |
          curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/profiles/Anime%201080p.yml" -o anime_1080p_upstream.yml

      - name: Update local anime 1080p.yml if different
        run: |
          if ! cmp -s anime_1080p.yml anime_1080p_upstream.yml; then
            echo "Updating anime_1080p.yml with upstream changes"
            mv anime_1080p_upstream.yml anime_1080p.yml
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
          else
            echo "anime_1080p.yml is already up to date"
          fi

      - name: Parse custom formats from anime 1080p.yml
        id: parse_formats
        run: |
          FORMATS=$(yq e '.custom_formats[].name' anime_1080p.yml)
          FORMATS_OUTPUT=$(echo "$FORMATS" | paste -sd "," -)
          echo "formats=$FORMATS_OUTPUT" >> $GITHUB_OUTPUT

      - name: Download required custom formats
        run: |
          BASE_URL="https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/custom_formats"
          mkdir -p custom_formats
          echo "${{ steps.parse_formats.outputs.formats }}" | tr ',' '\n' | while read -r FORMAT; do
              FILE_NAME="$FORMAT.yml"
              URL="$BASE_URL/$(echo "$FILE_NAME" | sed 's/ /%20/g')"
              echo "Downloading $FILE_NAME"
              curl -fsSL "$URL" -o "custom_formats/$FILE_NAME" || echo "Warning: $FILE_NAME not found"
          done

      - name: Extract regex patterns
        run: |
          mkdir -p temp_patterns
          > regex_patterns.txt
          for FILE in custom_formats/*.yml; do
              yq e '.conditions[].name' "$FILE" >> temp_patterns/regex_patterns_raw.txt
          done
          sort -u temp_patterns/regex_patterns_raw.txt > regex_patterns.txt
          rm -rf temp_patterns
          echo "Regex patterns extracted:"
          cat regex_patterns.txt

      - name: Commit and push changes
        run: |
          git add anime_1080p.yml custom_formats/*.yml regex_patterns.txt
          if ! git diff --cached --quiet; then
              git commit -m "Sync anime 1080p.yml, custom_formats, and regex_patterns"
              git push
          else
              echo "No changes to commit"
          fi
