name: Sync Anime 1080p and Custom Formats

on:
  schedule:
    - cron: '0 4 * * *' # Runs daily at 04:00 UTC
  workflow_dispatch:

jobs:
  sync_anime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl wget git
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Download latest Anime 1080p.yml
      run: |
        mkdir -p profiles
        curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/profiles/Anime%201080p.yml" -o profiles/Anime\ 1080p.yml

    - name: Parse custom formats from Anime 1080p.yml
      id: parse_formats
      run: |
        CUSTOM_FORMATS=$(yq e '.custom_formats[]' profiles/Anime\ 1080p.yml)
        echo "Custom formats referenced in Anime 1080p.yml:"
        echo "$CUSTOM_FORMATS"
        # Save to output for next steps
        echo "formats<<EOF" >> $GITHUB_OUTPUT
        echo "$CUSTOM_FORMATS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Download custom formats
      run: |
        mkdir -p custom_formats
        for FORMAT in ${{ steps.parse_formats.outputs.formats }}; do
          SAFE_FORMAT=$(echo "$FORMAT" | sed 's/ /%20/g')
          echo "Downloading custom format $FORMAT"
          curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/custom_formats/$SAFE_FORMAT.yml" -o "custom_formats/$FORMAT.yml" || echo "Warning: $FORMAT.yml not found"
        done

    - name: Extract regex patterns
      run: |
        mkdir -p regex_patterns
        > regex_patterns/regex_patterns.txt
        for FILE in custom_formats/*.yml; do
          yq e '.conditions[].name' "$FILE" >> regex_patterns/regex_patterns_raw.txt
        done
        sort -u regex_patterns/regex_patterns_raw.txt > regex_patterns/regex_patterns.txt
        rm -f regex_patterns/regex_patterns_raw.txt
        echo "Extracted regex patterns:"
        cat regex_patterns/regex_patterns.txt

    - name: Commit and push updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add profiles/Anime\ 1080p.yml custom_formats/ regex_patterns/
        git commit -m "Sync Anime 1080p.yml, custom_formats, and regex_patterns" || echo "No changes to commit"
        git push
