name: Sync Anime 1080p

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git wget jq

      - name: Download latest Anime 1080p.yml
        run: |
          mkdir -p profiles
          curl -fsSL https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/profiles/Anime%201080p.yml -o profiles/Anime\ 1080p.yml

      - name: Parse custom formats
        run: |
          CUSTOM_FORMATS=$(yq e -o=j '.custom_formats[].name' profiles/Anime\ 1080p.yml)
          echo "Custom formats referenced in Anime 1080p.yml:"
          echo "$CUSTOM_FORMATS" | jq -r '.[]'
          echo "$CUSTOM_FORMATS" > custom_formats_list.json

      - name: Download custom formats
        run: |
          mkdir -p custom_formats
          jq -r '.[]' custom_formats_list.json | while read -r FORMAT; do
            SAFE_FORMAT=$(echo "$FORMAT" | sed 's/ /%20/g')
            DEST="custom_formats/$FORMAT.yml"
            echo "Downloading custom format: $FORMAT"
            curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/custom_formats/$SAFE_FORMAT.yml" -o "$DEST" || echo "Warning: $FORMAT.yml not found"
          done

      - name: Extract regex patterns from custom formats
        run: |
          mkdir -p regex_patterns
          > regex_patterns.txt
          for FILE in custom_formats/*.yml; do
              yq e -o=j '.conditions[] | select(.type=="release_title") | .name' "$FILE" | while read -r PATTERN; do
                  PATTERN=$(echo "$PATTERN" | sed 's/^"\(.*\)"$/\1/')
                  echo "$PATTERN" >> regex_patterns.txt
              done
          done
          sort -u regex_patterns.txt -o regex_patterns.txt
          echo "Regex patterns found:"
          cat regex_patterns.txt

      - name: Download regex patterns
        run: |
          while read -r PATTERN; do
            SAFE_PATTERN=$(echo "$PATTERN" | sed 's/ /%20/g')
            DEST="regex_patterns/$PATTERN.yml"
            echo "Downloading regex pattern $PATTERN"
            curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/regex_patterns/$SAFE_PATTERN.yml" -o "$DEST" || echo "Warning: $PATTERN.yml not found"
          done < regex_patterns.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add profiles/Anime\ 1080p.yml custom_formats/ regex_patterns/
          git diff-index --quiet HEAD || git commit -m "Sync Anime 1080p.yml, custom_formats, and regex_patterns"
          git push
