name: Dictionarry Sync

on:
  schedule:
    - cron: "0 2 * * *" # runs daily at 2am UTC
  workflow_dispatch: # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history so merge works

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Dictionarry-Hub/database.git
          git fetch upstream

      - name: Merge upstream stable into main
        run: |
          git checkout main
          git merge upstream/stable --no-edit || {
            echo "Merge failed due to conflicts. Please resolve manually.";
            exit 1;
          }

      - name: Push changes
        run: |
          git push origin main
