name: Dry Run Sync Anime 1080p Custom Formats

on:
  workflow_dispatch:

jobs:
  dry_run_custom_formats:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl git wget
          # Install Mike Farah yq (Go version)
          YQ_VERSION=v4.45.1
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Download latest anime 1080p.yml
        run: |
          curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/profiles/Anime%201080p.yml" -o anime_1080p.yml

      - name: Parse custom formats from anime 1080p.yml
        id: parse_formats
        run: |
          FORMATS=($(yq e '.custom_formats[].name' anime_1080p.yml))
          echo "Custom formats found in anime 1080p.yml:"
          printf "  - %s\n" "${FORMATS[@]}"
          echo "formats=${FORMATS[*]}" >> $GITHUB_OUTPUT

      - name: Dry run download of required custom formats
        run: |
          BASE_URL="https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/custom_formats"
          echo "Dry run: The following custom formats would be downloaded/updated:"
          for f in ${{ steps.parse_formats.outputs.formats }}; do
            FILE_NAME="$f.yml"
            URL="$BASE_URL/$(echo $FILE_NAME | sed 's/ /%20/g')"
            echo "  - $FILE_NAME from $URL"
          done

      - name: Dry run extraction of regex patterns
        run: |
          echo "Dry run: The following regex patterns would be extracted from the custom formats:"
          for f in ${{ steps.parse_formats.outputs.formats }}; do
            FILE_NAME="$f.yml"
            echo "  - Patterns from $FILE_NAME (example output using yq parsing)"
          done

      - name: Dry run summary of changes
        run: |
          echo "Dry run complete. No files were overwritten or committed."
          echo "Summary:"
          echo "  - anime 1080p.yml would be updated"
          echo "  - The above custom_formats would be updated/added"
          echo "  - regex_patterns.txt would be regenerated"
