name: Sync Anime Profile (Dry Run)

on:
  workflow_dispatch:       # Manual trigger only

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          repository: serversathome/profilarr
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target

      - name: Checkout upstream repo
        uses: actions/checkout@v4
        with:
          repository: sweatyeggs69/profilarr
          ref: stable
          path: upstream

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Copy Anime profile
        run: |
          mkdir -p target/profiles
          cp "upstream/profiles/Anime 1080p.yml" "target/profiles/"
          echo "Synced: profiles/Anime 1080p.yml" >> $GITHUB_STEP_SUMMARY

      - name: Copy dependent custom_formats
        id: copy_formats
        run: |
          mkdir -p target/custom_formats
          deps=""
          for cf_name in $(yq e '.custom_formats[].name' upstream/profiles/"Anime 1080p.yml"); do
            match=$(grep -rl "name: ${cf_name}" upstream/custom_formats || true)
            if [ -n "$match" ]; then
              fname=$(basename "$match")
              echo "Syncing custom_formats/$fname"
              cp "$match" "target/custom_formats/$fname"
              echo "Synced: custom_formats/$fname" >> $GITHUB_STEP_SUMMARY
              deps="$deps target/custom_formats/$fname"
            else
              echo "⚠️ No matching custom_format found for '${cf_name}'" | tee -a $GITHUB_STEP_SUMMARY
            fi
          done
          echo "custom_formats=$deps" >> $GITHUB_OUTPUT

      - name: Copy dependent regex_patterns
        run: |
          mkdir -p target/regex_patterns
          for cf in ${{ steps.copy_formats.outputs.custom_formats }}; do
            for rp_name in $(yq e '.conditions[].name' "$cf" | sort -u); do
              if [ -f "upstream/regex_patterns/${rp_name}.yml" ]; then
                echo "Syncing regex_patterns/${rp_name}.yml"
                cp "upstream/regex_patterns/${rp_name}.yml" "target/regex_patterns/${rp_name}.yml"
                echo "Synced: regex_patterns/${rp_name}.yml" >> $GITHUB_STEP_SUMMARY
              else
                echo "⚠️ Regex pattern ${rp_name}.yml not found upstream" | tee -a $GITHUB_STEP_SUMMARY
              fi
            done
          done

      - name: Show what would change (dry run)
        run: |
          cd target
          git add profiles/Anime\ 1080p.yml custom_formats/ regex_patterns/

          echo "## Changed or Added Files" >> $GITHUB_STEP_SUMMARY
          git status --short >> $GITHUB_STEP_SUMMARY

          echo "## Diff of Changes" >> $GITHUB_STEP_SUMMARY
          git diff --cached >> $GITHUB_STEP_SUMMARY
