name: Dry Run Sync Anime 1080p Custom Formats with Regex Patterns

on:
  workflow_dispatch:

jobs:
  dry_run_custom_formats:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and yq
        run: |
          sudo apt-get update && sudo apt-get install -y curl git wget
          # Install Mike Farah yq (Go version) to $HOME/bin
          mkdir -p $HOME/bin
          YQ_VERSION=v4.45.1
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O $HOME/bin/yq
          chmod +x $HOME/bin/yq
          export PATH=$HOME/bin:$PATH
          yq --version

      - name: Download latest anime 1080p.yml
        run: |
          curl -fsSL "https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/profiles/Anime%201080p.yml" -o anime_1080p.yml

      - name: Parse custom formats from anime 1080p.yml
        id: parse_formats
        run: |
          echo "Custom formats found in anime 1080p.yml:"
          FORMATS=$(yq e '.custom_formats[].name' anime_1080p.yml)
          echo "$FORMATS" | while read -r FORMAT; do
              echo "  - $FORMAT"
          done
          FORMATS_OUTPUT=$(echo "$FORMATS" | paste -sd "," -)
          echo "formats=$FORMATS_OUTPUT" >> $GITHUB_OUTPUT

      - name: Dry run download of required custom formats
        run: |
          BASE_URL="https://raw.githubusercontent.com/sweatyeggs69/profilarr/stable/custom_formats"
          mkdir -p temp_custom_formats
          echo "Dry run: The following custom formats would be downloaded/updated:"
          echo "${{ steps.parse_formats.outputs.formats }}" | tr ',' '\n' | while read -r FORMAT; do
              FILE_NAME="$FORMAT.yml"
              URL="$BASE_URL/$(echo "$FILE_NAME" | sed 's/ /%20/g')"
              echo "  - $FILE_NAME from $URL"
              # Download into temp folder for regex pattern extraction
              curl -fsSL "$URL" -o "temp_custom_formats/$FILE_NAME" || echo "Warning: $FILE_NAME not found"
          done

      - name: Dry run extraction of regex patterns
        run: |
          echo "Dry run: The following regex patterns would be extracted and deduplicated:"
          touch regex_patterns.txt
          for FILE in temp_custom_formats/*.yml; do
              yq e '.conditions[].name' "$FILE" >> regex_patterns_raw.txt
          done
          sort -u regex_patterns_raw.txt >> regex_patterns.txt
          rm regex_patterns_raw.txt
          cat regex_patterns.txt

      - name: Dry run summary of changes
        run: |
          echo "Dry run complete. No files were overwritten or committed."
          echo "Summary:"
          echo "  - anime 1080p.yml would be updated"
          echo "  - The downloaded custom_formats would be updated/added"
          echo "  - regex_patterns.txt would be regenerated with the following content:"
          cat regex_patterns.txt
