name: Sync Anime Profile (Dry Run)

on:
  workflow_dispatch:       # Manual trigger only

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: serversathome/profilarr
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target

      - name: Checkout upstream repo
        uses: actions/checkout@v4
        with:
          repository: sweatyeggs69/profilarr
          ref: stable
          path: upstream

      - name: Install yq & dos2unix
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Ensure target directory exists
        run: mkdir -p target/profiles target/custom_formats target/regex_patterns

      - name: Sync Anime 1080p profile
        run: |
          # Force overwrite
          cp upstream/profiles/Anime\ 1080p.yml target/profiles/
          # Normalize line endings to avoid git diff issues
          dos2unix target/profiles/Anime\ 1080p.yml
          echo "Synced: profiles/Anime 1080p.yml" >> $GITHUB_STEP_SUMMARY

      - name: Sync dependent custom_formats
        id: copy_formats
        run: |
          deps=""
          for cf_name in $(yq e '.custom_formats[].name // empty' upstream/profiles/"Anime 1080p.yml"); do
            match=$(grep -rl "name: ${cf_name}" upstream/custom_formats || true)
            if [ -n "$match" ]; then
              fname=$(basename "$match")
              cp "$match" "target/custom_formats/$fname"
              dos2unix "target/custom_formats/$fname"
              echo "Synced: custom_formats/$fname" >> $GITHUB_STEP_SUMMARY
              deps="$deps target/custom_formats/$fname"
            else
              echo "⚠️ No matching custom_format found for '${cf_name}'" | tee -a $GITHUB_STEP_SUMMARY
            fi
          done
          echo "custom_formats=$deps" >> $GITHUB_OUTPUT

      - name: Sync dependent regex_patterns
        run: |
          for cf in ${{ steps.copy_formats.outputs.custom_formats }}; do
            for rp_name in $(yq e '.conditions[].name // empty' "$cf" | sort -u); do
              if [ -f "upstream/regex_patterns/${rp_name}.yml" ]; then
                cp "upstream/regex_patterns/${rp_name}.yml" "target/regex_patterns/${rp_name}.yml"
                dos2unix "target/regex_patterns/${rp_name}.yml"
                echo "Synced: regex_patterns/${rp_name}.yml" >> $GITHUB_STEP_SUMMARY
              else
                echo "⚠️ Regex pattern ${rp_name}.yml not found upstream" | tee -a $GITHUB_STEP_SUMMARY
              fi
            done
          done

      - name: Show complete diff (dry run)
        run: |
          echo "## Diff of Anime 1080p.yml"
          diff -u target/profiles/Anime\ 1080p.yml upstream/profiles/Anime\ 1080p.yml || true >> $GITHUB_STEP_SUMMARY

          echo "## Changed or Added Files"
          git -C target status --short >> $GITHUB_STEP_SUMMARY
