name: Notify Groups

on:
  push:
    branches:
      - 1080p-Encode

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WORKFLOW_AUTOMATION_TOKEN }}
          repository: Dictionarry-Hub/groups
          event-type: database-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
