name: Sync Profilarr Database

permissions:
  contents: write  # allows pushing changes to repo

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Dictionarry-Hub/database.git
          git fetch upstream

      - name: Fast-forward main to upstream/stable (excluding workflow files)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git checkout main

          # Reset all files except workflows to match upstream/stable
          git checkout upstream/stable -- . ':(exclude).github/workflows/'

          # Commit any changes
          if ! git diff --quiet; then
            git add .
            git commit -m "Sync Dictionarry-Hub/database (excluding workflows)"
            git push origin main
          else
            echo "No changes to commit"
          fi
