name: Sync Profilarr Database

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Dictionarry-Hub/database.git
          git fetch upstream

      - name: Fast-forward main to upstream/stable
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Reset main branch to match upstream/stable
          git checkout main
          git reset --hard upstream/stable

          # Push changes to origin
          git push origin main --force
